-- MIGRATION UP START
CREATE TABLE raw_cards (
    id UUID PRIMARY KEY,
    lang TEXT NOT NULL,
    object JSON NOT NULL
)
-- MIGRATION UP END

-- MIGRATION DOWN START
DROP TABLE raw_cards;
-- MIGRATION DOWN END
