-- MIGRATION UP START
CREATE TABLE IF NOT EXISTS scryfall_history (
    url VARCHAR NOT NULL,
    headers TEXT,
    response_code INTEGER,
    error TEXT,
    _id INTEGER PRIMARY KEY AUTOINCREMENT,
    _requested_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
-- MIGRATION UP END

-- MIGRATION DOWN START
DROP TABLE IF EXISTS scryfall_history;
-- MIGRATION DOWN END
